# SINCE I DON'T KNOW LINUX THIS WAS GENERATED BY AI
#!/bin/bash
# check if venv folder exists
if [ -d venv ]; then
  # activate the virtual environment
  source venv/scripts/activate
else
  # call one_click.py
  python3 one_click.py
fi
# run main.py
python3 main.py
