name: Build and Package

on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Make
        run: choco install make

      - name: Install dependencies
        run: make install SHELL=cmd

      - name: Build the project
        run: make build SHELL=cmd

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: TF2-GPTChatBot-win-${{ github.sha }}
          path: frontend/dist/win-unpacked/
