name: Build and Package

on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            shell: cmd
            make_install_command: choco install make
            artifact_path: frontend/dist/win-unpacked/
            artifact_name: TF2-GPTChatBot-win-${{ github.sha }}
          - os: ubuntu-latest
            shell: bash
            make_install_command: sudo apt-get install -y make
            artifact_path: frontend/dist/linux-unpacked/
            artifact_name: TF2-GPTChatBot-linux-${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Make
        run: ${{ matrix.make_install_command }}

      - name: Install dependencies
        run: make install SHELL=${{ matrix.shell }}

      - name: Build the project
        run: make build SHELL=${{ matrix.shell }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}
